-- Monthly AI allowance and one-time credit packs.
create table if not exists public.billing_credit_ledger (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references auth.users(id) on delete cascade,
  credits integer not null check (credits <> 0),
  source text not null check (source in ('monthly_plan', 'credit_pack', 'ai_usage', 'admin_adjustment')),
  stripe_event_id text,
  stripe_session_id text,
  period_start date,
  created_at timestamptz not null default now()
);

create unique index if not exists billing_credit_ledger_stripe_event_uidx
  on public.billing_credit_ledger(stripe_event_id) where stripe_event_id is not null;
create index if not exists billing_credit_ledger_profile_idx
  on public.billing_credit_ledger(profile_id, created_at desc);

alter table public.billing_credit_ledger enable row level security;
drop policy if exists billing_credit_ledger_select_own on public.billing_credit_ledger;
create policy billing_credit_ledger_select_own on public.billing_credit_ledger
  for select using (auth.uid() = profile_id);

grant select on public.billing_credit_ledger to authenticated;
grant all on public.billing_credit_ledger to service_role;
grant usage, select on sequence public.billing_credit_ledger_id_seq to service_role;
