begin;

create table if not exists public.financial_import_batches (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  file_name text not null,
  file_type text not null,
  file_size bigint not null check (file_size > 0 and file_size <= 10485760),
  source_type text not null check (source_type in ('xlsx', 'csv', 'pdf')),
  storage_path text not null,
  status text not null default 'preview' check (status in ('preview', 'processing', 'confirmed', 'cancelled', 'failed')),
  detected_mapping jsonb not null default '{}'::jsonb,
  summary jsonb not null default '{}'::jsonb,
  row_count integer not null default 0 check (row_count >= 0),
  valid_count integer not null default 0 check (valid_count >= 0),
  duplicate_count integer not null default 0 check (duplicate_count >= 0),
  error_count integer not null default 0 check (error_count >= 0),
  confirmed_at timestamptz,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists financial_import_batches_profile_created_idx
  on public.financial_import_batches(profile_id, created_at desc);

create table if not exists public.financial_import_rows (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.financial_import_batches(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  row_index integer not null check (row_index > 0),
  movement_type text not null check (movement_type in ('gasto', 'ingreso')),
  occurred_at timestamptz,
  description text,
  amount numeric(18, 2),
  category text check (category is null or category in ('Vida', 'Placeres', 'Futuro')),
  subcategory text,
  currency text not null default 'MXN',
  status text not null default 'ready' check (status in ('ready', 'invalid', 'duplicate', 'imported', 'skipped')),
  validation_errors text[] not null default '{}'::text[],
  fingerprint text not null,
  source_data jsonb not null default '{}'::jsonb,
  target_table text check (target_table is null or target_table in ('gastos', 'ingresos')),
  target_id bigint,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  unique (batch_id, row_index)
);

create index if not exists financial_import_rows_profile_batch_idx
  on public.financial_import_rows(profile_id, batch_id, row_index);

create index if not exists financial_import_rows_profile_fingerprint_idx
  on public.financial_import_rows(profile_id, fingerprint);

alter table public.gastos
  add column if not exists import_batch_id uuid references public.financial_import_batches(id) on delete set null,
  add column if not exists import_fingerprint text;

alter table public.ingresos
  add column if not exists origen text not null default 'Web',
  add column if not exists import_batch_id uuid references public.financial_import_batches(id) on delete set null,
  add column if not exists import_fingerprint text;

alter table public.gastos
  drop constraint if exists gastos_origen_check;

alter table public.gastos
  add constraint gastos_origen_check
  check (origen in ('Web', 'Telegram', 'Banco', 'Archivo'));

alter table public.ingresos
  drop constraint if exists ingresos_origen_check;

alter table public.ingresos
  add constraint ingresos_origen_check
  check (origen in ('Web', 'Telegram', 'Banco', 'Archivo'));

create unique index if not exists gastos_profile_import_fingerprint_uidx
  on public.gastos(profile_id, import_fingerprint)
  where import_fingerprint is not null;

create unique index if not exists ingresos_profile_import_fingerprint_uidx
  on public.ingresos(profile_id, import_fingerprint)
  where import_fingerprint is not null;

create index if not exists gastos_import_batch_idx
  on public.gastos(import_batch_id)
  where import_batch_id is not null;

create index if not exists ingresos_import_batch_idx
  on public.ingresos(import_batch_id)
  where import_batch_id is not null;

alter table public.financial_import_batches enable row level security;
alter table public.financial_import_rows enable row level security;

drop policy if exists "Financial import batches belong to authenticated profile" on public.financial_import_batches;
create policy "Financial import batches belong to authenticated profile"
  on public.financial_import_batches
  for all
  to authenticated
  using (profile_id = (select auth.uid()))
  with check (profile_id = (select auth.uid()));

drop policy if exists "Financial import rows belong to authenticated profile" on public.financial_import_rows;
create policy "Financial import rows belong to authenticated profile"
  on public.financial_import_rows
  for all
  to authenticated
  using (profile_id = (select auth.uid()))
  with check (profile_id = (select auth.uid()));

revoke all on table public.financial_import_batches from anon, authenticated;
revoke all on table public.financial_import_rows from anon, authenticated;
revoke all on sequence public.financial_import_rows_id_seq from anon, authenticated;
grant all on table public.financial_import_batches to service_role;
grant all on table public.financial_import_rows to service_role;
grant usage, select on sequence public.financial_import_rows_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'financial-imports',
  'financial-imports',
  false,
  10485760,
  array[
    'application/pdf',
    'text/csv',
    'application/csv',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]::text[]
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

commit;
